name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test:cov
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
